### ISSUE TITLE
week 01 回覆

### ISSUE THREAD

**Issue by azole** [yez1125/git-practice#1]
內容可以再更豐富一些，試著把老師給的問題當作「起點」，讓自己去挑戰做得更好，也讓自己有更多好奇一些，除了老師問的問題外，你自己對 git 還沒有什麼好奇的、想了解的地方？

**Comment by yez1125** [comment]
在聽完上次的課之後，才發現有些底層的邏輯是值得我們去學習的，近期應該會花點時間研究這塊，整理至git.md，順便練習markdown XD

**Comment by azole** [comment]
ok 沒有其他要討論的，就可以先 close 這個 issue 了。
